### ISSUE TITLE
/run.sh: exec: line 80: /usr/share/grafana/bin/grafana-server: not found

### ISSUE THREAD

**Issue by budbach** [alexswilliams/arm32-v6-grafana-docker#1]
Alex, Have you got this working in past?  Getting:

```
$ docker run alexswilliams/arm32v6-grafana:6.3.3
/run.sh: exec: line 80: /usr/share/grafana/bin/grafana-server: not found
```
from the latest image and tried the 6.0.2 version with the same results.

Peeking in the container, it looks like the server is where it should be:

```
$ docker run -it --entrypoint /bin/ash alexswilliams/arm32v6-grafana:6.3.3
$ ls -la /usr/share/grafana/bin/grafana-server
-rwxr-xr-x    1 root     root      40462616 Aug 16  2019 /usr/share/grafana/bin/grafana-server
/usr/share/grafana $ /usr/share/grafana/bin/grafana-server
/bin/ash: /usr/share/grafana/bin/grafana-server: not found
```

Any ideas on how to fix this?

**Comment by alexswilliams** [comment]
Hi there,

I seem to remember anything from grafana 6 had build issues using this method.  The last one I successfully got working was `5.4.3`, which is pushed to dockerhub.

I would be tempted to say the 6.x.x images on dockerhub are probably dudds, and should be removed.  I remember there being two issues with the current approach for building this image:
 - builds requiring more resource than was available on a rasp 1B, so couldn't be done natively
 - builds failing under docker's armhf emulation support because of a bug in the go compiler that fails when running in qemu
Given that, I suspect the pushed images for 6.x.x are actually going to include the arm32v7 server image published from github; and based on that, my suspicion is that the executable within the image is the wrong architecture, but it's just a hunch.

Will see if I can get a grafana 7 image working.

**Comment by budbach** [comment]
That would be awesome.  I was able to get grafana 7 running on the Pi Zero bare metal from the grafana binaries.  Could not find a good base image to build a container from though but I am far from an expert.

**Comment by alexswilliams** [comment]
`docker pull alexswilliams/arm32v6-grafana:7.0.3` on a raspi running armv6 should now give you an image that runs.
Ended up taking a hybrid approach - take the UI from the versioned tarball, and then compile the backend from scratch.
Give it a try, shout if it doesn't work :)

**Comment by budbach** [comment]
Awesome!  Works great.
